import SwiftUI
import FoundationModels

struct CreateIssueView: View {
    let owner: String
    let repo: String
    let issueService: IssueService
    let onCreated: () -> Void

    @Environment(\.dismiss) private var dismiss
    @AppStorage("quickMentionText") private var quickMentionText = "@claude"

    @State private var title = ""
    @State private var descriptionText = ""
    @State private var isSubmitting = false
    @State private var isGeneratingTitle = false
    @State private var errorMessage: String?
    @State private var showError = false

    private var canGenerateTitle: Bool {
        SystemLanguageModel.default.isAvailable && descriptionText.count > 20 && !isGeneratingTitle
    }

    var body: some View {
        #if targetEnvironment(macCatalyst)
        macOSLayout
        #else
        iOSLayout
        #endif
    }

    // MARK: - macOS Layout

    private var macOSLayout: some View {
        VStack(spacing: 0) {
            // Header
            HStack {
                Text("New Issue")
                    .font(.title2)
                    .fontWeight(.semibold)
                Spacer()
            }
            .padding(.horizontal, 24)
            .padding(.top, 24)
            .padding(.bottom, 16)

            Divider()

            // Form content
            ScrollView {
                VStack(alignment: .leading, spacing: 24) {
                    // Title section
                    VStack(alignment: .leading, spacing: 8) {
                        Text("Title")
                            .font(.headline)
                            .foregroundStyle(.secondary)
                        HStack(spacing: 8) {
                            TextField("Issue title (autogenerated when empty)", text: $title)
                                .textFieldStyle(.roundedBorder)
                            if SystemLanguageModel.default.isAvailable {
                                Button {
                                    Task { await generateTitle() }
                                } label: {
                                    if isGeneratingTitle {
                                        ProgressView()
                                            .controlSize(.small)
                                    } else {
                                        Image(systemName: "sparkles")
                                    }
                                }
                                .buttonStyle(.bordered)
                                .disabled(!canGenerateTitle)
                                .help("Generate title from description")
                            }
                        }
                    }

                    // Description section
                    VStack(alignment: .leading, spacing: 8) {
                        HStack {
                            Text("Description")
                                .font(.headline)
                                .foregroundStyle(.secondary)

                            Spacer()

                            Button {
                                insertMention()
                            } label: {
                                Text(quickMentionText)
                                    .font(.subheadline)
                            }
                            .buttonStyle(.bordered)
                            .controlSize(.small)
                        }
                        TextEditor(text: $descriptionText)
                            .frame(minHeight: 200)
                            .overlay(
                                RoundedRectangle(cornerRadius: 6)
                                    .stroke(Color(uiColor: .separator), lineWidth: 1)
                            )
                    }
                }
                .padding(24)
            }

            Divider()

            // Footer with buttons
            HStack {
                Spacer()
                Button("Cancel") {
                    dismiss()
                }
                .buttonStyle(.bordered)
                .keyboardShortcut(.cancelAction)

                Button("Create Issue") {
                    Task { await createIssue() }
                }
                .buttonStyle(.borderedProminent)
                .keyboardShortcut(.defaultAction)
                .disabled((title.isEmpty && descriptionText.count <= 20) || isSubmitting)
            }
            .padding(20)
            .background(.ultraThinMaterial)
        }
        .frame(minWidth: 500, minHeight: 450)
        .alert("Error", isPresented: $showError) {
            Button("OK", role: .cancel) { }
        } message: {
            Text(errorMessage ?? "Unknown error")
        }
    }

    // MARK: - iOS Layout

    private var iOSLayout: some View {
        NavigationStack {
            Form {
                Section("Title") {
                    HStack {
                        TextField("Issue title (autogenerated when empty)", text: $title)
                        if SystemLanguageModel.default.isAvailable {
                            Button {
                                Task { await generateTitle() }
                            } label: {
                                if isGeneratingTitle {
                                    ProgressView()
                                        .controlSize(.small)
                                } else {
                                    Image(systemName: "sparkles")
                                        .foregroundStyle(.tint)
                                }
                            }
                            .buttonStyle(.plain)
                            .disabled(!canGenerateTitle)
                        }
                    }
                }

                Section {
                    TextEditor(text: $descriptionText)
                        .frame(minHeight: 150)
                } header: {
                    HStack {
                        Text("Description")

                        Spacer()

                        Button {
                            insertMention()
                        } label: {
                            Text(quickMentionText)
                                .font(.caption)
                        }
                    }
                }
            }
            .navigationTitle("New Issue")
            .navigationBarTitleDisplayMode(.inline)
            .toolbarBackground(.ultraThinMaterial, for: .navigationBar)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        dismiss()
                    }
                }

                ToolbarItem(placement: .confirmationAction) {
                    Button("Create") {
                        Task { await createIssue() }
                    }
                    .buttonStyle(.borderedProminent)
                    .disabled((title.isEmpty && descriptionText.count <= 20) || isSubmitting)
                }
            }
            .alert("Error", isPresented: $showError) {
                Button("OK", role: .cancel) { }
            } message: {
                Text(errorMessage ?? "Unknown error")
            }
        }
    }

    private func generateTitle() async {
        isGeneratingTitle = true
        defer { isGeneratingTitle = false }

        do {
            let session = LanguageModelSession()
            let prompt = """
            Generate a concise issue title (maximum 10 words) for this bug report or feature request:

            \(descriptionText)

            Respond with only the title text, no quotes, prefixes, or explanation.
            """
            let response = try await session.respond(to: prompt)
            title = response.content.trimmingCharacters(in: .whitespacesAndNewlines)
        } catch {
            // Silent fail - user can still type manually
        }
    }

    private func insertMention() {
        if descriptionText.isEmpty {
            descriptionText = quickMentionText + " "
        } else if descriptionText.hasSuffix("\n") || descriptionText.hasSuffix(" ") {
            descriptionText += quickMentionText + " "
        } else {
            descriptionText += " " + quickMentionText + " "
        }
    }

    private func createIssue() async {
        isSubmitting = true

        // Auto-generate title if empty but description has content
        if title.isEmpty && descriptionText.count > 20 {
            await generateTitle()
        }

        do {
            _ = try await issueService.createIssue(
                owner: owner,
                repo: repo,
                title: title,
                body: descriptionText
            )
            onCreated()
            dismiss()
        } catch {
            errorMessage = error.localizedDescription
            showError = true
        }

        isSubmitting = false
    }
}
