import SwiftUI
import PhotosUI
import FoundationModels

struct CreateIssueView: View {
    let owner: String
    let repo: String
    let issueService: IssueService
    let attachmentService: AttachmentService
    let onCreated: () -> Void

    @Environment(\.dismiss) private var dismiss
    @AppStorage("quickMentionText") private var quickMentionText = "@claude"

    @State private var title = ""
    @State private var descriptionText = ""
    @State private var isSubmitting = false
    @State private var isGeneratingTitle = false
    @State private var errorMessage: String?
    @State private var showError = false

    // Attachment state
    @State private var selectedPhotos: [PhotosPickerItem] = []
    @State private var pendingAttachments: [PendingAttachment] = []
    @State private var isLoadingPhotos = false

    private var canGenerateTitle: Bool {
        SystemLanguageModel.default.isAvailable && descriptionText.count > 20 && !isGeneratingTitle
    }

    var body: some View {
        #if targetEnvironment(macCatalyst)
        macOSLayout
        #else
        iOSLayout
        #endif
    }

    // MARK: - macOS Layout

    private var macOSLayout: some View {
        VStack(spacing: 0) {
            // Header
            HStack {
                Text("New Issue")
                    .font(.title2)
                    .fontWeight(.semibold)
                Spacer()
            }
            .padding(.horizontal, 24)
            .padding(.top, 24)
            .padding(.bottom, 16)

            Divider()

            // Form content
            ScrollView {
                VStack(alignment: .leading, spacing: 24) {
                    // Title section
                    VStack(alignment: .leading, spacing: 8) {
                        Text("Title")
                            .font(.headline)
                            .foregroundStyle(.secondary)
                        HStack(spacing: 8) {
                            TextField("Issue title (autogenerated when empty)", text: $title)
                                .textFieldStyle(.roundedBorder)
                            if SystemLanguageModel.default.isAvailable {
                                Button {
                                    Task { await generateTitle() }
                                } label: {
                                    if isGeneratingTitle {
                                        ProgressView()
                                            .controlSize(.small)
                                    } else {
                                        Image(systemName: "sparkles")
                                    }
                                }
                                .buttonStyle(.bordered)
                                .disabled(!canGenerateTitle)
                                .help("Generate title from description")
                            }
                        }
                    }

                    // Description section
                    VStack(alignment: .leading, spacing: 8) {
                        HStack {
                            Text("Description")
                                .font(.headline)
                                .foregroundStyle(.secondary)

                            Spacer()

                            Button {
                                insertMention()
                            } label: {
                                Text(quickMentionText)
                                    .font(.subheadline)
                            }
                            .buttonStyle(.bordered)
                            .controlSize(.small)
                        }
                        TextEditor(text: $descriptionText)
                            .frame(minHeight: 200)
                            .overlay(
                                RoundedRectangle(cornerRadius: 6)
                                    .stroke(Color(uiColor: .separator), lineWidth: 1)
                            )
                    }

                    // Attachments section
                    VStack(alignment: .leading, spacing: 8) {
                        Text("Attachments")
                            .font(.headline)
                            .foregroundStyle(.secondary)

                        if pendingAttachments.isEmpty {
                            PhotosPicker(
                                selection: $selectedPhotos,
                                maxSelectionCount: 10,
                                matching: .any(of: [.images, .screenshots])
                            ) {
                                SwiftUI.Label("Add Images", systemImage: "photo.on.rectangle.angled")
                            }
                            .buttonStyle(.bordered)
                        } else {
                            HStack(alignment: .top, spacing: 8) {
                                LazyVGrid(columns: [GridItem(.adaptive(minimum: 72), spacing: 8)], alignment: .leading, spacing: 8) {
                                    ForEach(pendingAttachments) { attachment in
                                        PendingAttachmentThumbnailView(attachment: attachment) {
                                            pendingAttachments.removeAll { $0.id == attachment.id }
                                        }
                                    }
                                }

                                Spacer()

                                PhotosPicker(
                                    selection: $selectedPhotos,
                                    maxSelectionCount: 10,
                                    matching: .any(of: [.images, .screenshots])
                                ) {
                                    Image(systemName: "plus")
                                        .font(.title3)
                                        .frame(width: 72, height: 72)
                                        .background(Color(uiColor: .tertiarySystemFill))
                                        .clipShape(RoundedRectangle(cornerRadius: 8))
                                }
                                .buttonStyle(.plain)
                            }
                        }

                        if isLoadingPhotos {
                            HStack {
                                ProgressView()
                                    .controlSize(.small)
                                Text("Loading photos...")
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                            }
                        }
                    }
                }
                .padding(24)
            }

            Divider()

            // Footer with buttons
            HStack {
                Spacer()
                Button("Cancel") {
                    dismiss()
                }
                .buttonStyle(.bordered)
                .keyboardShortcut(.cancelAction)

                Button("Create Issue") {
                    Task { await createIssue() }
                }
                .buttonStyle(.borderedProminent)
                .keyboardShortcut(.defaultAction)
                .disabled((title.isEmpty && descriptionText.count <= 20) || isSubmitting)
            }
            .padding(20)
            .background(.ultraThinMaterial)
        }
        .frame(minWidth: 500, minHeight: 450)
        .alert("Error", isPresented: $showError) {
            Button("OK", role: .cancel) { }
        } message: {
            Text(errorMessage ?? "Unknown error")
        }
        .onChange(of: selectedPhotos) { _, newValue in
            if !newValue.isEmpty {
                Task { await loadSelectedPhotos() }
            }
        }
    }

    // MARK: - iOS Layout

    private var iOSLayout: some View {
        NavigationStack {
            Form {
                Section("Title") {
                    HStack {
                        TextField("Issue title (autogenerated when empty)", text: $title)
                        if SystemLanguageModel.default.isAvailable {
                            Button {
                                Task { await generateTitle() }
                            } label: {
                                if isGeneratingTitle {
                                    ProgressView()
                                        .controlSize(.small)
                                } else {
                                    Image(systemName: "sparkles")
                                        .foregroundStyle(.tint)
                                }
                            }
                            .buttonStyle(.plain)
                            .disabled(!canGenerateTitle)
                        }
                    }
                }

                Section {
                    TextEditor(text: $descriptionText)
                        .frame(minHeight: 150)
                } header: {
                    HStack {
                        Text("Description")

                        Spacer()

                        Button {
                            insertMention()
                        } label: {
                            Text(quickMentionText)
                                .font(.caption)
                        }
                    }
                }

                Section("Attachments") {
                    if pendingAttachments.isEmpty && !isLoadingPhotos {
                        PhotosPicker(
                            selection: $selectedPhotos,
                            maxSelectionCount: 10,
                            matching: .any(of: [.images, .screenshots])
                        ) {
                            SwiftUI.Label("Add Images", systemImage: "photo.on.rectangle.angled")
                        }
                    } else {
                        if isLoadingPhotos {
                            HStack {
                                ProgressView()
                                    .controlSize(.small)
                                Text("Loading photos...")
                                    .font(.subheadline)
                                    .foregroundStyle(.secondary)
                            }
                        }

                        if !pendingAttachments.isEmpty {
                            ScrollView(.horizontal, showsIndicators: false) {
                                HStack(spacing: 8) {
                                    ForEach(pendingAttachments) { attachment in
                                        PendingAttachmentThumbnailView(attachment: attachment) {
                                            pendingAttachments.removeAll { $0.id == attachment.id }
                                        }
                                    }

                                    PhotosPicker(
                                        selection: $selectedPhotos,
                                        maxSelectionCount: 10,
                                        matching: .any(of: [.images, .screenshots])
                                    ) {
                                        Image(systemName: "plus")
                                            .font(.title3)
                                            .frame(width: 72, height: 72)
                                            .background(Color(uiColor: .tertiarySystemFill))
                                            .clipShape(RoundedRectangle(cornerRadius: 8))
                                    }
                                    .buttonStyle(.plain)
                                }
                            }
                        }
                    }
                }
            }
            .navigationTitle("New Issue")
            .navigationBarTitleDisplayMode(.inline)
            .toolbarBackground(.ultraThinMaterial, for: .navigationBar)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        dismiss()
                    }
                }

                ToolbarItem(placement: .confirmationAction) {
                    Button("Create") {
                        Task { await createIssue() }
                    }
                    .buttonStyle(.borderedProminent)
                    .disabled((title.isEmpty && descriptionText.count <= 20) || isSubmitting)
                }
            }
            .alert("Error", isPresented: $showError) {
                Button("OK", role: .cancel) { }
            } message: {
                Text(errorMessage ?? "Unknown error")
            }
            .onChange(of: selectedPhotos) { _, newValue in
                if !newValue.isEmpty {
                    Task { await loadSelectedPhotos() }
                }
            }
        }
    }

    private func generateTitle() async {
        isGeneratingTitle = true
        defer { isGeneratingTitle = false }

        do {
            let session = LanguageModelSession()
            let prompt = """
            Generate a concise issue title (maximum 10 words) for this bug report or feature request:

            \(descriptionText)

            Respond with only the title text, no quotes, prefixes, or explanation.
            """
            let response = try await session.respond(to: prompt)
            title = response.content.trimmingCharacters(in: .whitespacesAndNewlines)
        } catch {
            // Silent fail - user can still type manually
        }
    }

    private func insertMention() {
        if descriptionText.isEmpty {
            descriptionText = quickMentionText + " "
        } else if descriptionText.hasSuffix("\n") || descriptionText.hasSuffix(" ") {
            descriptionText += quickMentionText + " "
        } else {
            descriptionText += " " + quickMentionText + " "
        }
    }

    private func createIssue() async {
        isSubmitting = true

        // Auto-generate title if empty but description has content
        if title.isEmpty && descriptionText.count > 20 {
            await generateTitle()
        }

        do {
            // Create the issue first
            let createdIssue = try await issueService.createIssue(
                owner: owner,
                repo: repo,
                title: title,
                body: descriptionText
            )

            // Upload attachments if any
            for attachment in pendingAttachments {
                _ = try await attachmentService.uploadIssueAttachment(
                    owner: owner,
                    repo: repo,
                    index: createdIssue.number,
                    data: attachment.data,
                    fileName: attachment.fileName,
                    mimeType: attachment.mimeType
                )
            }

            onCreated()
            dismiss()
        } catch {
            errorMessage = error.localizedDescription
            showError = true
        }

        isSubmitting = false
    }

    private func loadSelectedPhotos() async {
        guard !selectedPhotos.isEmpty else { return }

        isLoadingPhotos = true
        defer {
            isLoadingPhotos = false
            selectedPhotos = []
        }

        for item in selectedPhotos {
            do {
                if let data = try await item.loadTransferable(type: Data.self) {
                    // Determine file name and type
                    let fileName: String
                    let mimeType: String

                    if let contentType = item.supportedContentTypes.first {
                        let ext = contentType.preferredFilenameExtension ?? "jpg"
                        fileName = "image_\(UUID().uuidString.prefix(8)).\(ext)"
                        mimeType = contentType.preferredMIMEType ?? "image/jpeg"
                    } else {
                        fileName = "image_\(UUID().uuidString.prefix(8)).jpg"
                        mimeType = "image/jpeg"
                    }

                    // Create thumbnail
                    let thumbnailData: Data?
                    if let uiImage = UIImage(data: data) {
                        let maxSize: CGFloat = 200
                        let scale = min(maxSize / uiImage.size.width, maxSize / uiImage.size.height, 1.0)
                        let newSize = CGSize(
                            width: uiImage.size.width * scale,
                            height: uiImage.size.height * scale
                        )
                        let renderer = UIGraphicsImageRenderer(size: newSize)
                        let thumbnail = renderer.image { _ in
                            uiImage.draw(in: CGRect(origin: .zero, size: newSize))
                        }
                        thumbnailData = thumbnail.jpegData(compressionQuality: 0.7)
                    } else {
                        thumbnailData = nil
                    }

                    let pending = PendingAttachment(
                        data: data,
                        fileName: fileName,
                        mimeType: mimeType,
                        thumbnail: thumbnailData
                    )
                    pendingAttachments.append(pending)
                }
            } catch {
                // Skip failed items
                continue
            }
        }
    }
}

// MARK: - Photo Loading Modifier

extension CreateIssueView {
    @ViewBuilder
    func withPhotoLoading() -> some View {
        self.onChange(of: selectedPhotos) { _, newValue in
            if !newValue.isEmpty {
                Task {
                    await loadSelectedPhotos()
                }
            }
        }
    }
}
