import SwiftUI
import FoundationModels

struct CreatePullRequestView: View {
    let owner: String
    let repo: String
    let pullRequestService: PullRequestService
    let repositoryService: RepositoryService
    let onCreated: () -> Void

    // Optional prefilled values (from URL)
    var initialTitle: String?
    var initialBody: String?
    var initialHeadBranch: String?
    var initialBaseBranch: String?

    @Environment(\.dismiss) private var dismiss
    @AppStorage("prTitlePrompt") private var prTitlePrompt = "Generate a concise pull request title (maximum 10 words) for this code change.\nRespond with only the title text, no quotes, prefixes, or explanation."

    @State private var title = ""
    @State private var descriptionText = ""
    @State private var headBranch = ""
    @State private var baseBranch = ""
    @State private var branches: [Branch] = []
    @State private var isLoadingBranches = true
    @State private var isSubmitting = false
    @State private var isGeneratingTitle = false
    @State private var errorMessage: String?
    @State private var showError = false
    @State private var hasAppliedInitialValues = false

    // Dictation state
    @State private var dictationManager = DictationManager()
    @State private var showDictationPermissionAlert = false
    @State private var textBeforeDictation = ""
    @State private var cursorPositionAtDictationStart: Int = 0
    @State private var selectedRange: NSRange?

    private var canGenerateTitle: Bool {
        SystemLanguageModel.default.isAvailable && descriptionText.count > 20 && !isGeneratingTitle
    }

    var body: some View {
        #if targetEnvironment(macCatalyst)
        macOSLayout
        #else
        iOSLayout
        #endif
    }

    // MARK: - macOS Layout

    private var macOSLayout: some View {
        VStack(spacing: 0) {
            // Header
            HStack {
                Text("New Pull Request")
                    .font(.title2)
                    .fontWeight(.semibold)
                Spacer()
            }
            .padding(.horizontal, 24)
            .padding(.top, 24)
            .padding(.bottom, 16)

            Divider()

            // Form content
            ScrollView {
                VStack(alignment: .leading, spacing: 24) {
                    // Branches section
                    VStack(alignment: .leading, spacing: 12) {
                        Text("Branches")
                            .font(.headline)
                            .foregroundStyle(.secondary)

                        if isLoadingBranches {
                            HStack {
                                Spacer()
                                ProgressView()
                                Spacer()
                            }
                            .padding(.vertical, 20)
                        } else {
                            VStack(spacing: 12) {
                                HStack {
                                    Text("Source branch")
                                        .frame(width: 100, alignment: .leading)
                                    Picker("", selection: $headBranch) {
                                        Text("Select branch").tag("")
                                        ForEach(branches) { branch in
                                            Text(branch.name).tag(branch.name)
                                        }
                                    }
                                    .labelsHidden()
                                }

                                HStack {
                                    Text("Target branch")
                                        .frame(width: 100, alignment: .leading)
                                    Picker("", selection: $baseBranch) {
                                        Text("Select branch").tag("")
                                        ForEach(branches) { branch in
                                            Text(branch.name).tag(branch.name)
                                        }
                                    }
                                    .labelsHidden()
                                }
                            }
                        }
                    }

                    // Title section
                    VStack(alignment: .leading, spacing: 8) {
                        Text("Title")
                            .font(.headline)
                            .foregroundStyle(.secondary)
                        HStack(spacing: 8) {
                            TextField("PR title (autogenerated when empty)", text: $title)
                                .textFieldStyle(.roundedBorder)
                            if SystemLanguageModel.default.isAvailable {
                                Button {
                                    Task { await generateTitle() }
                                } label: {
                                    if isGeneratingTitle {
                                        ProgressView()
                                            .controlSize(.small)
                                    } else {
                                        Image(systemName: "sparkles")
                                    }
                                }
                                .buttonStyle(.bordered)
                                .disabled(!canGenerateTitle)
                                .help("Generate title from description")
                            }
                        }
                    }

                    // Description section
                    VStack(alignment: .leading, spacing: 8) {
                        Text("Description")
                            .font(.headline)
                            .foregroundStyle(.secondary)
                        ZStack(alignment: .bottomTrailing) {
                            TextEditorWithSelection(text: $descriptionText, selectedRange: $selectedRange)
                                .frame(minHeight: 150)
                                .overlay(
                                    RoundedRectangle(cornerRadius: 6)
                                        .stroke(Color(uiColor: .separator), lineWidth: 1)
                                )

                            // Dictation button
                            Button {
                                Task { await handleDictation() }
                            } label: {
                                Image(systemName: dictationManager.isRecording ? "mic.fill" : "mic")
                                    .font(.title3)
                                    .foregroundStyle(dictationManager.isRecording ? .red : .secondary)
                                    .symbolEffect(.pulse, isActive: dictationManager.isRecording)
                                    .frame(width: 44, height: 44)
                                    .contentShape(Rectangle())
                            }
                            .buttonStyle(.plain)
                            .padding(4)
                        }
                    }
                }
                .padding(24)
            }

            Divider()

            // Footer with buttons
            HStack {
                Spacer()
                Button("Cancel") {
                    dismiss()
                }
                .buttonStyle(.bordered)
                .keyboardShortcut(.cancelAction)

                Button("Create Pull Request") {
                    Task { await createPullRequest() }
                }
                .buttonStyle(.borderedProminent)
                .keyboardShortcut(.defaultAction)
                .disabled(!isFormValidForSubmit || isSubmitting)
            }
            .padding(20)
            .background(.ultraThinMaterial)
        }
        .frame(minWidth: 540, minHeight: 520)
        .alert("Error", isPresented: $showError) {
            Button("OK", role: .cancel) { }
        } message: {
            Text(errorMessage ?? "Unknown error")
        }
        .task {
            await loadBranches()
        }
    }

    // MARK: - iOS Layout

    private var iOSLayout: some View {
        NavigationStack {
            Form {
                Section("Branches") {
                    if isLoadingBranches {
                        HStack {
                            Spacer()
                            ProgressView()
                            Spacer()
                        }
                    } else {
                        Picker("Source branch", selection: $headBranch) {
                            Text("Select branch").tag("")
                            ForEach(branches) { branch in
                                Text(branch.name).tag(branch.name)
                            }
                        }

                        Picker("Target branch", selection: $baseBranch) {
                            Text("Select branch").tag("")
                            ForEach(branches) { branch in
                                Text(branch.name).tag(branch.name)
                            }
                        }
                    }
                }

                Section("Title") {
                    HStack {
                        TextField("PR title (autogenerated when empty)", text: $title)
                        if SystemLanguageModel.default.isAvailable {
                            Button {
                                Task { await generateTitle() }
                            } label: {
                                if isGeneratingTitle {
                                    ProgressView()
                                        .controlSize(.small)
                                } else {
                                    Image(systemName: "sparkles")
                                        .foregroundStyle(.tint)
                                }
                            }
                            .buttonStyle(.plain)
                            .disabled(!canGenerateTitle)
                        }
                    }
                }

                Section("Description") {
                    ZStack(alignment: .bottomTrailing) {
                        TextEditorWithSelection(text: $descriptionText, selectedRange: $selectedRange)
                            .frame(minHeight: 150)

                        // Dictation button
                        Button {
                            Task { await handleDictation() }
                        } label: {
                            Image(systemName: dictationManager.isRecording ? "mic.fill" : "mic")
                                .font(.title3)
                                .foregroundStyle(dictationManager.isRecording ? .red : .secondary)
                                .symbolEffect(.pulse, isActive: dictationManager.isRecording)
                                .frame(width: 44, height: 44)
                                .contentShape(Rectangle())
                        }
                        .buttonStyle(.plain)
                    }
                }
            }
            .navigationTitle("New Pull Request")
            .navigationBarTitleDisplayMode(.inline)
            .toolbarBackground(.ultraThinMaterial, for: .navigationBar)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        dismiss()
                    }
                }

                ToolbarItem(placement: .confirmationAction) {
                    Button("Create") {
                        Task { await createPullRequest() }
                    }
                    .buttonStyle(.borderedProminent)
                    .disabled(!isFormValidForSubmit || isSubmitting)
                }
            }
            .alert("Error", isPresented: $showError) {
                Button("OK", role: .cancel) { }
            } message: {
                Text(errorMessage ?? "Unknown error")
            }
            .alert("Microphone Access Required", isPresented: $showDictationPermissionAlert) {
                Button("Open Settings") {
                    if let url = URL(string: UIApplication.openSettingsURLString) {
                        UIApplication.shared.open(url)
                    }
                }
                Button("Cancel", role: .cancel) { }
            } message: {
                Text("Please enable microphone and speech recognition access in Settings to use dictation.")
            }
            .task {
                await loadBranches()
            }
            .onAppear {
                setupDictation()
            }
            .onDisappear {
                dictationManager.stopRecording()
            }
        }
    }

    private var isFormValid: Bool {
        !title.isEmpty && !headBranch.isEmpty && !baseBranch.isEmpty && headBranch != baseBranch
    }

    private var isFormValidForSubmit: Bool {
        // Allow submission without title if description is long enough (will auto-generate)
        let hasValidTitle = !title.isEmpty || descriptionText.count > 20
        return hasValidTitle && !headBranch.isEmpty && !baseBranch.isEmpty && headBranch != baseBranch
    }

    private func generateTitle() async {
        isGeneratingTitle = true
        defer { isGeneratingTitle = false }

        do {
            let session = LanguageModelSession()
            let prompt = """
            \(prTitlePrompt)

            \(descriptionText)
            """
            let response = try await session.respond(to: prompt)
            title = response.content.trimmingCharacters(in: .whitespacesAndNewlines)
        } catch {
            // Silent fail - user can still type manually
        }
    }

    private func setupDictation() {
        dictationManager.onTranscription = { transcription, isFinal in
            // Insert at cursor position (not just append)
            let insertPosition = cursorPositionAtDictationStart
            let beforeCursor = String(textBeforeDictation.prefix(insertPosition))
            let afterCursor = String(textBeforeDictation.dropFirst(insertPosition))

            // Process transcription for mid-sentence insertion
            var processedTranscription = transcription

            // Lowercase first letter if inserting mid-sentence (after a letter/word)
            if let lastChar = beforeCursor.last,
               lastChar.isLetter || lastChar == " ",
               let firstChar = processedTranscription.first,
               firstChar.isUppercase {
                processedTranscription = processedTranscription.prefix(1).lowercased() + processedTranscription.dropFirst()
            }

            // Add space before if needed
            let needsSpaceBefore = !beforeCursor.isEmpty &&
                !beforeCursor.hasSuffix(" ") &&
                !beforeCursor.hasSuffix("\n")
            let spaceBefore = needsSpaceBefore ? " " : ""

            // Add space after if there's text following and it doesn't start with space/punctuation
            let needsSpaceAfter = !afterCursor.isEmpty &&
                !afterCursor.hasPrefix(" ") &&
                !afterCursor.hasPrefix("\n") &&
                !(afterCursor.first?.isPunctuation ?? false)
            let spaceAfter = needsSpaceAfter ? " " : ""

            descriptionText = beforeCursor + spaceBefore + processedTranscription + spaceAfter + afterCursor
        }
    }

    private func handleDictation() async {
        if dictationManager.permissionDenied {
            showDictationPermissionAlert = true
            return
        }

        // Save current text and cursor position before starting recording
        if !dictationManager.isRecording {
            textBeforeDictation = descriptionText
            // Use cursor position if available, otherwise append at end
            cursorPositionAtDictationStart = selectedRange?.location ?? descriptionText.count
        }

        await dictationManager.toggleRecording()
        if dictationManager.permissionDenied {
            showDictationPermissionAlert = true
        }
    }

    private func loadBranches() async {
        isLoadingBranches = true

        do {
            branches = try await repositoryService.getBranches(owner: owner, repo: repo)

            // Apply initial values if provided (from URL)
            if !hasAppliedInitialValues {
                hasAppliedInitialValues = true

                if let initialTitle {
                    title = initialTitle
                }
                if let initialBody {
                    descriptionText = initialBody
                }
                if let initialBaseBranch, branches.contains(where: { $0.name == initialBaseBranch }) {
                    baseBranch = initialBaseBranch
                } else if let defaultBranch = branches.first(where: { $0.name == "main" || $0.name == "master" }) {
                    // Fallback to default base branch
                    baseBranch = defaultBranch.name
                }
                if let initialHeadBranch, branches.contains(where: { $0.name == initialHeadBranch }) {
                    headBranch = initialHeadBranch
                }
            }
        } catch {
            errorMessage = "Failed to load branches: \(error.localizedDescription)"
            showError = true
        }

        isLoadingBranches = false
    }

    private func createPullRequest() async {
        isSubmitting = true

        // Auto-generate title if empty but description has content
        if title.isEmpty && descriptionText.count > 20 {
            await generateTitle()
        }

        do {
            _ = try await pullRequestService.createPullRequest(
                owner: owner,
                repo: repo,
                title: title,
                body: descriptionText,
                head: headBranch,
                base: baseBranch
            )
            onCreated()
            dismiss()
        } catch {
            errorMessage = error.localizedDescription
            showError = true
        }

        isSubmitting = false
    }
}
